<script>
    try{

        console.log("Line 1")
        console.log(Line2)
        console.log("line in try")

    }
    catch(error){
        console.log(error.name + " " + error.message);
        console.log("inside catch block");

    }

    console.log("line after try catch")
</script>